#!/bin/bash

# Generate TypeScript client from OpenAPI specification
# This script generates API client code for the frontend

set -e

echo "🚀 Generating TypeScript API client from OpenAPI specification..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
OPENAPI_SPEC="./openapi.yaml"
OUTPUT_DIR="./packages/ui/src/services/api"
TEMP_DIR="./tmp/openapi-gen"

# Check if OpenAPI spec exists
if [ ! -f "$OPENAPI_SPEC" ]; then
    echo -e "${RED}❌ OpenAPI specification not found at $OPENAPI_SPEC${NC}"
    exit 1
fi

# Create output directory
echo -e "${BLUE}📁 Creating output directory: $OUTPUT_DIR${NC}"
mkdir -p "$OUTPUT_DIR"

# Clean previous generation
if [ -d "$TEMP_DIR" ]; then
    rm -rf "$TEMP_DIR"
fi
mkdir -p "$TEMP_DIR"

echo -e "${BLUE}🔧 Generating TypeScript client...${NC}"

# Generate client using openapi-typescript-codegen
npx openapi-typescript-codegen \
    --input "$OPENAPI_SPEC" \
    --output "$TEMP_DIR" \
    --client axios \
    --name ApiClient \
    --useOptions true \
    --useUnionTypes true \
    --exportCore true \
    --exportServices true \
    --exportModels true \
    --exportSchemas false

# Check if generation was successful
if [ ! -d "$TEMP_DIR" ]; then
    echo -e "${RED}❌ Failed to generate client code${NC}"
    exit 1
fi

echo -e "${BLUE}📦 Moving generated files to output directory...${NC}"

# Copy generated files to the UI package
cp -r "$TEMP_DIR"/* "$OUTPUT_DIR/"

# Clean up temp directory
rm -rf "$TEMP_DIR"

# Generate index file for easy imports
cat > "$OUTPUT_DIR/index.ts" << 'EOF'
// Auto-generated API client exports
// This file is generated by tools/scripts/generate-client.sh
// Do not edit manually

export * from './models';
export * from './services';
export { ApiClient } from './ApiClient';
export { OpenAPI } from './core/OpenAPI';

// Re-export commonly used types
export type {
  MCPServer,
  ServerListResponse,
  User,
  ApiKey,
  PublishServerRequest,
  CreateApiKeyRequest,
  HealthResponse,
  MCPHealthResponse
} from './models';
EOF

# Create configuration file for the API client
cat > "$OUTPUT_DIR/config.ts" << 'EOF'
// API Client Configuration
import { OpenAPI } from './core/OpenAPI';

export interface ApiConfig {
  baseUrl: string;
  token?: string;
  apiKey?: string;
}

export function configureApiClient(config: ApiConfig): void {
  OpenAPI.BASE = config.baseUrl;
  
  if (config.token) {
    OpenAPI.TOKEN = config.token;
  }
  
  if (config.apiKey) {
    OpenAPI.HEADERS = {
      ...OpenAPI.HEADERS,
      'Authorization': `ApiKey ${config.apiKey}`
    };
  }
}

// Default configuration for different environments
export const API_CONFIG = {
  development: {
    baseUrl: 'http://localhost:3010'
  },
  staging: {
    baseUrl: 'https://staging-mcp-registry.company.com'
  },
  production: {
    baseUrl: 'https://mcp-registry.company.com'
  }
} as const;

// Get current environment configuration
export function getApiConfig(): ApiConfig {
  const env = process.env.NODE_ENV || 'development';
  return API_CONFIG[env as keyof typeof API_CONFIG] || API_CONFIG.development;
}
EOF

# Generate React hooks for the API client
mkdir -p "$OUTPUT_DIR/hooks"

cat > "$OUTPUT_DIR/hooks/index.ts" << 'EOF'
// React hooks for API client
// This file provides React Query hooks for API calls

export * from './useServers';
export * from './useAuth';
export * from './useApiKeys';
export * from './useHealth';
EOF

cat > "$OUTPUT_DIR/hooks/useServers.ts" << 'EOF'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ServersService } from '../services';
import type { MCPServer, PublishServerRequest, ServerFilters } from '../models';

// Query keys
export const serverKeys = {
  all: ['servers'] as const,
  lists: () => [...serverKeys.all, 'list'] as const,
  list: (filters: ServerFilters) => [...serverKeys.lists(), filters] as const,
  details: () => [...serverKeys.all, 'detail'] as const,
  detail: (id: string) => [...serverKeys.details(), id] as const,
};

// Get all servers with filtering
export function useServers(filters: ServerFilters = {}) {
  return useQuery({
    queryKey: serverKeys.list(filters),
    queryFn: () => ServersService.getServers(filters),
    staleTime: 30 * 1000, // 30 seconds
  });
}

// Get single server by ID
export function useServer(id: string) {
  return useQuery({
    queryKey: serverKeys.detail(id),
    queryFn: () => ServersService.getServerById(id),
    enabled: !!id,
  });
}

// Publish new server
export function usePublishServer() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: PublishServerRequest) => ServersService.publishServer(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: serverKeys.lists() });
    },
  });
}
EOF

cat > "$OUTPUT_DIR/hooks/useAuth.ts" << 'EOF'
import { useMutation, useQuery } from '@tanstack/react-query';
import { AuthService } from '../services';
import type { User } from '../models';

// Query keys
export const authKeys = {
  me: ['auth', 'me'] as const,
};

// Get current user
export function useMe() {
  return useQuery({
    queryKey: authKeys.me,
    queryFn: () => AuthService.getCurrentUser(),
    retry: false,
  });
}

// Login mutation
export function useLogin() {
  return useMutation({
    mutationFn: (credentials: { email: string; password: string }) =>
      AuthService.login(credentials),
  });
}

// Register mutation
export function useRegister() {
  return useMutation({
    mutationFn: (data: { email: string; username: string; password: string; adminKey?: string }) =>
      AuthService.register(data),
  });
}
EOF

cat > "$OUTPUT_DIR/hooks/useApiKeys.ts" << 'EOF'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { ApiKeysService } from '../services';
import type { ApiKey, CreateApiKeyRequest, UpdateApiKeyRequest, ApiKeyFilters } from '../models';

// Query keys
export const apiKeyKeys = {
  all: ['apiKeys'] as const,
  lists: () => [...apiKeyKeys.all, 'list'] as const,
  list: (filters: ApiKeyFilters) => [...apiKeyKeys.lists(), filters] as const,
  details: () => [...apiKeyKeys.all, 'detail'] as const,
  detail: (id: string) => [...apiKeyKeys.details(), id] as const,
};

// Get all API keys
export function useApiKeys(filters: ApiKeyFilters = {}) {
  return useQuery({
    queryKey: apiKeyKeys.list(filters),
    queryFn: () => ApiKeysService.getApiKeys(filters),
  });
}

// Get single API key by ID
export function useApiKey(id: string) {
  return useQuery({
    queryKey: apiKeyKeys.detail(id),
    queryFn: () => ApiKeysService.getApiKeyById(id),
    enabled: !!id,
  });
}

// Create new API key
export function useCreateApiKey() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (data: CreateApiKeyRequest) => ApiKeysService.createApiKey(data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: apiKeyKeys.lists() });
    },
  });
}

// Update API key
export function useUpdateApiKey() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateApiKeyRequest }) =>
      ApiKeysService.updateApiKey(id, data),
    onSuccess: (_, { id }) => {
      queryClient.invalidateQueries({ queryKey: apiKeyKeys.lists() });
      queryClient.invalidateQueries({ queryKey: apiKeyKeys.detail(id) });
    },
  });
}

// Delete API key
export function useDeleteApiKey() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (id: string) => ApiKeysService.deleteApiKey(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: apiKeyKeys.lists() });
    },
  });
}
EOF

cat > "$OUTPUT_DIR/hooks/useHealth.ts" << 'EOF'
import { useQuery } from '@tanstack/react-query';
import { HealthService } from '../services';

// Query keys
export const healthKeys = {
  general: ['health'] as const,
  mcp: ['health', 'mcp'] as const,
  metrics: ['health', 'metrics'] as const,
};

// General health check
export function useHealth() {
  return useQuery({
    queryKey: healthKeys.general,
    queryFn: () => HealthService.getHealth(),
    refetchInterval: 30 * 1000, // 30 seconds
  });
}

// MCP protocol health check
export function useMcpHealth() {
  return useQuery({
    queryKey: healthKeys.mcp,
    queryFn: () => HealthService.getMcpHealth(),
    refetchInterval: 30 * 1000, // 30 seconds
  });
}

// Metrics endpoint
export function useMetrics() {
  return useQuery({
    queryKey: healthKeys.metrics,
    queryFn: () => HealthService.getMetrics(),
    refetchInterval: 60 * 1000, // 1 minute
  });
}
EOF

echo -e "${GREEN}✅ API client generated successfully!${NC}"
echo -e "${BLUE}📍 Generated files:${NC}"
echo -e "   • API client: $OUTPUT_DIR"
echo -e "   • Models and services: $OUTPUT_DIR/models, $OUTPUT_DIR/services"
echo -e "   • React hooks: $OUTPUT_DIR/hooks"
echo -e "   • Configuration: $OUTPUT_DIR/config.ts"

echo -e "${YELLOW}📝 Next steps:${NC}"
echo -e "   1. Import the API client in your UI components"
echo -e "   2. Configure the base URL for your environment"
echo -e "   3. Use the React Query hooks for data fetching"
echo -e ""
echo -e "${GREEN}🎉 Client generation complete!${NC}"